
package com.slaoui.enterprise.prototypes.soap.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GestionEmployes", targetNamespace = "http://jaxws.soap.prototypes.enterprise.slaoui.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GestionEmployes {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.slaoui.enterprise.prototypes.soap.jaxws.CreateEmpployesResponse
     */
    @WebMethod(action = "http://jaxws.soap.prototypes.enterprise.slaoui.com/createEmployes")
    @WebResult(name = "createEmpployesResponse", targetNamespace = "http://jaxws.soap.prototypes.enterprise.slaoui.com/", partName = "parameters")
    public CreateEmpployesResponse createEmployes(
        @WebParam(name = "createEmpployesRequest", targetNamespace = "http://jaxws.soap.prototypes.enterprise.slaoui.com/", partName = "parameters")
        CreateEmpployesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.slaoui.enterprise.prototypes.soap.jaxws.GetEmployesByIDResponse
     */
    @WebMethod(action = "http://jaxws.soap.prototypes.enterprise.slaoui.com/getEmployesByID")
    @WebResult(name = "getEmployesByIDResponse", targetNamespace = "http://jaxws.soap.prototypes.enterprise.slaoui.com/", partName = "parameters")
    public GetEmployesByIDResponse getEmployesByID(
        @WebParam(name = "getEmployesByIDRequest", targetNamespace = "http://jaxws.soap.prototypes.enterprise.slaoui.com/", partName = "parameters")
        GetEmployesByIDRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.slaoui.enterprise.prototypes.soap.jaxws.GetAllEmployesResponse
     */
    @WebMethod(action = "http://jaxws.soap.prototypes.enterprise.slaoui.com/getAllEmployes")
    @WebResult(name = "getAllEmployesResponse", targetNamespace = "http://jaxws.soap.prototypes.enterprise.slaoui.com/", partName = "parameters")
    public GetAllEmployesResponse getAllEmployes(
        @WebParam(name = "getAllEmployesRequest", targetNamespace = "http://jaxws.soap.prototypes.enterprise.slaoui.com/", partName = "parameters")
        GetAllEmployesRequest parameters);

}
